// WEB-SCREENSHOT CAPTURE TEMPLATE
//
// Plain ESM JavaScript so Node 18+ runs it directly — no Bun, no TypeScript,
// no build step. Generated by the `web-screenshot` Claude Code skill.
//
// Usage (capture.mjs can live anywhere; WEB_SCREENSHOT_RUNTIME tells it where
// puppeteer-core was installed):
//   WEB_SCREENSHOT_RUNTIME=$RUNTIME CHROME=... URL=... OUT=... node /path/to/capture.mjs
//
// Why createRequire: Node ESM resolves `import 'puppeteer-core'` from the
// script's own directory, NOT cwd. Since this template lives in /tmp/ and
// puppeteer-core is in ~/.cache/web-screenshot/runtime/node_modules/, plain
// `import` fails. createRequire lets us load CJS modules from an arbitrary
// base path — puppeteer-core ships both CJS and ESM, so this works fine.
import { createRequire } from 'node:module';
import { mkdirSync } from 'node:fs';

const RUNTIME = process.env.WEB_SCREENSHOT_RUNTIME;
if (!RUNTIME) {
  console.error('ERROR: WEB_SCREENSHOT_RUNTIME env var required (path to runtime dir with node_modules/puppeteer-core)');
  process.exit(1);
}
const require = createRequire(`file://${RUNTIME}/`);
const puppeteer = require('puppeteer-core');

// ===== ENV =====
const CHROME = process.env.CHROME;
if (!CHROME) {
  console.error('ERROR: CHROME env var required (path to chrome-headless-shell)');
  process.exit(1);
}
const URL = process.env.URL || 'http://localhost:3000';
const OUT = process.env.OUT || '/tmp/screenshots';
const VIEWPORT = {
  width: Number(process.env.VW || 1440),
  height: Number(process.env.VH || 900),
  deviceScaleFactor: Number(process.env.DPR || 2),  // 2 = retina, sharp on README
};

// ===== LAUNCH =====
const browser = await puppeteer.launch({
  executablePath: CHROME,
  headless: 'shell',                  // chrome-headless-shell mode (NOT `true`)
  args: [
    '--no-sandbox',
    '--disable-gpu',
    '--hide-scrollbars',              // no ugly scrollbar on the right of every shot
    '--disable-features=PaintHolding', // headless prefers raw frames over hold-and-fade
  ],
});

try {
  const page = await browser.newPage();
  await page.setViewport(VIEWPORT);

  // Don't use networkidle0 — pages that auto-refresh (dashboards with polling)
  // never settle. domcontentloaded + a fixed wait works for most apps.
  console.log(`navigating to ${URL}...`);
  await page.goto(URL, { waitUntil: 'domcontentloaded', timeout: 30_000 });
  await new Promise(r => setTimeout(r, Number(process.env.INITIAL_WAIT_MS || 4_000)));

  mkdirSync(OUT, { recursive: true });

  // ============================================================
  // SHOTS — edit per user request. Delete unused examples.
  // ============================================================

  // ---- Pattern 1: full page ----
  // For a simple "give me the whole page as one image":
  //
  //   await page.screenshot({ path: `${OUT}/full.png`, fullPage: true });

  // ---- Pattern 2: element self-shot (PREFERRED when possible) ----
  // Cleanest mode — puppeteer crops exactly to the element's bounding rect.
  //
  //   const el = await page.$('#some-selector');
  //   if (!el) throw new Error('selector not found: #some-selector');
  //   await el.screenshot({ path: `${OUT}/01-element.png` });

  // ---- Pattern 3: clip up to an anchor element ----
  // "Give me the top of the page, stop before the footer/comments/etc."
  //
  //   const anchorTop = await page.evaluate(() => {
  //     const el = document.getElementById('anchor');
  //     return el ? Math.round(el.getBoundingClientRect().top + window.scrollY) : 1000;
  //   });
  //   await page.screenshot({
  //     path: `${OUT}/02-clip-to-anchor.png`,
  //     clip: { x: 0, y: 0, width: VIEWPORT.width, height: anchorTop },
  //   });

  // ---- Pattern 4: interaction then screenshot ----
  // Click something, wait for the result, then screenshot the result element.
  // Use waitForFunction for state changes — DON'T hard-wait setTimeout.
  //
  //   await page.click('#trigger-button');
  //   await page.waitForFunction(
  //     () => !document.querySelector('.spinner'),  // wait for spinner to vanish
  //     { timeout: 60_000, polling: 500 },
  //   );
  //   const result = await page.$('#result');
  //   await result.screenshot({ path: `${OUT}/03-interaction.png` });

  // ---- Pattern 5: mobile / responsive shot ----
  // Override viewport for one shot.
  //
  //   await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 2 });
  //   await new Promise(r => setTimeout(r, 800));  // let CSS reflow
  //   await page.screenshot({ path: `${OUT}/04-mobile.png` });
  //   // Restore desktop viewport if more shots follow:
  //   await page.setViewport(VIEWPORT);

  // ============================================================

  console.log('done.');
} finally {
  await browser.close();
}
